# Makefile: Description
#
# Copyright: (c) 2017 Jacco van Schaik (jacco@jaccovanschaik.net)
# Created:   2017-05-13
# Version:   $Id: Makefile 426 2017-05-26 11:03:08Z jacco $
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

clean:
	$(RM) *.pyc

all:

install:
