# Makefile: Description
#
# Copyright: (c) 2017-2025 Jacco van Schaik (jacco@jaccovanschaik.net)
# Created:   2017-05-13
# Version:   $Id: Makefile 461 2022-01-31 09:02:30Z jacco $
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

clean:
	$(RM) -r core core-* *.pyc __pycache__

all:

install:
