# Makefile: Description
#
# Copyright:	(c) 2013 Jacco van Schaik (jacco@jaccovanschaik.net)
# Version:	$Id: Makefile 109 2013-10-14 18:34:37Z jacco $
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

.PHONY: tags test base clean install

all: libmx.so libmx.a mx

include tests/tests.mk

JVS_LIB = -L$(HOME)/lib -ljvs
JVS_INC = -I$(HOME)/include

INSTALL_TOP = $(HOME)
INSTALL_BIN = $(INSTALL_TOP)/bin
INSTALL_INC = $(INSTALL_TOP)/include
INSTALL_LIB = $(INSTALL_TOP)/lib
INSTALL_MAN = $(INSTALL_TOP)/man

MAKE_ALIB = ar rv
MAKE_SLIB = gcc -shared -o

LIBMX = libmx.o private.o
MX = mx.o private.o

CFLAGS = -g -fPIC $(JVS_INC) -D_GNU_SOURCE # -DPARANOID

libmx.so: $(LIBMX)
	$(MAKE_SLIB) libmx.so $(LIBMX)

libmx.a: $(LIBMX)
	$(MAKE_ALIB) libmx.a $(LIBMX)

mx: $(MX)
	$(CC) $(CFLAGS) -o $@ $(MX) $(JVS_LIB) -lm

test: mx $(TESTS)

base: $(BASES)

%: %.c libmx.a
	$(CC) $(CFLAGS) -I. -o $@ $^ $(JVS_LIB) libmx.a -lm

clean:
	rm -f *.o libmx.so libmx.a mx core vgcore.* libmx.tgz $(CLEAN)

libmx.tgz: clean
	tar cvf - `ls | grep -v libmx.tgz` | gzip > libmx.tgz

install: libmx.so libmx.a mx test
	if [ ! -d $(INSTALL_LIB) ]; then mkdirhier $(INSTALL_LIB); fi
	cp libmx.so libmx.a $(INSTALL_LIB)
	if [ ! -d $(INSTALL_INC) ]; then mkdirhier $(INSTALL_INC); fi
	cp libmx.h $(INSTALL_INC)
	if [ ! -d $(INSTALL_BIN) ]; then mkdirhier $(INSTALL_BIN); fi
	cp mx $(INSTALL_BIN)

tags:
	ctags -R /usr/include $(HOME)/src/libjvs .

# Dependencies - generated by deps on Wed Oct  9 19:43:56 CEST 2013

libmx.o: libmx.c libmx.h private.h 
mx.o: mx.c private.h 
private.o: private.c private.h 
